name: Modelops deploy
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  repository_dispatch:
    types: [ml_ci_cd]
jobs:
  ml_ci_cd:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Check Python version
      run: python --version

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Create data directory if not exists
      run: mkdir -p data

    - name: Download dataset
      run: wget -O data/data.csv ${{github.event.client_payload.dataseturl}}

    - name: Display dataset content
      run: cat data/data.csv

    - name: Train model
      run: python model/train.py

    - name: Build Docker image
      run: docker build -t ${{secrets.DOCKER_USER}}/${{secrets.MODEL_NAME}}:${{github.event.client_payload.sha}} .

    - name: Show Docker images
      run: docker images

    - name: Log in to DockerHub
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 

    - name: Push Docker image
      run: docker push ${{secrets.DOCKER_USER}}/${{secrets.MODEL_NAME}}:${{github.event.client_payload.sha}}
